name: Sync Fork

on:
  schedule:
    - cron: '* * */1 * *' # every 1 day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: kimwang1978
          base: tvbox
          head: main
